---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - python3-pip
    - python3-dev

- name: Move Requirements
  template:
    src: templates/requirements.txt
    dest: /home/ubuntu/requirements.txt

- name: Install Python Lib
  pip:
    requirements: /home/ubuntu/requirements.txt
    executable: pip3