---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - python3-pip
    - python3-dev
    - uwsgi
    - uwsgi-plugin-python3
- name: Create Directory
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
    recurse: yes

- name: Move Requirements
  copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/app/"
    owner: ubuntu
    mode: 0640
  with_fileglob:
    - "templates/*"

- name: Install Python Lib
  pip:
    requirements: /home/ubuntu/app/requirements.txt
    executable: pip3