---
- name: Install nginx
  apt: name=nginx state=present

#- name: delete Config
#  file:
#    path: /etc/nginx/sites-enabled/default state=absent

- name: write Config
  template:
    src: templates/default
    dest: /etc/nginx/sites-enabled/default

- name: uwsgi run
  command: uwsgi --ini /home/ubuntu/app/test.ini

- name: restart nginx
  command: service nginx restart
